-- Sample Products for TLSY Handicrafts
-- Run this after the main schema to populate with sample data

INSERT INTO products (
  product_name,
  product_name_tl,
  description,
  description_tl,
  short_description,
  short_description_tl,
  category,
  price,
  currency,
  images,
  specifications,
  turnaround_time,
  turnaround_time_tl,
  customization_available,
  availability,
  featured
) VALUES
-- Printing Services
(
  'Custom Business Cards',
  'Custom Business Cards',
  'Professional business cards printed on high-quality cardstock. Perfect for networking and making a lasting impression. Available in various finishes including matte, glossy, and textured.',
  'Propesyonal na business cards na naka-print sa high-quality cardstock. Perpekto para sa networking at paggawa ng lasting impression. Available sa iba''t ibang finishes kasama ang matte, glossy, at textured.',
  'Professional business cards on premium cardstock',
  'Propesyonal na business cards sa premium cardstock',
  'Printing Services',
  500.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Size": "3.5 x 2 inches", "Material": "Premium cardstock", "Quantity": "500 pieces"}'::jsonb,
  '3-5 business days',
  '3-5 araw ng negosyo',
  true,
  true,
  true
),
(
  'Personalized Invitations',
  'Personalized na Imbitasyon',
  'Beautiful custom invitations for any occasion. We work with you to create the perfect design that matches your event theme. High-quality printing with various paper options.',
  'Magagandang custom invitations para sa anumang okasyon. Nakikipagtulungan kami sa iyo upang lumikha ng perpektong disenyo na tumutugma sa tema ng iyong event. High-quality printing na may iba''t ibang paper options.',
  'Custom invitations for any occasion',
  'Custom invitations para sa anumang okasyon',
  'Invitations',
  350.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Size": "5 x 7 inches", "Quantity": "50 pieces", "Paper": "Premium cardstock"}'::jsonb,
  '5-7 business days',
  '5-7 araw ng negosyo',
  true,
  true,
  true
),
(
  'Custom Stickers',
  'Custom Stickers',
  'Vibrant, durable stickers perfect for branding, packaging, or personal use. Available in various shapes and sizes. Weather-resistant and long-lasting.',
  'Makulay at matibay na stickers na perpekto para sa branding, packaging, o personal na gamit. Available sa iba''t ibang hugis at laki. Weather-resistant at matagal.',
  'Vibrant custom stickers in any shape',
  'Makulay na custom stickers sa anumang hugis',
  'Printing Services',
  150.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Quantity": "100 sheets", "Material": "Vinyl", "Finish": "Glossy or Matte"}'::jsonb,
  '3-5 business days',
  '3-5 araw ng negosyo',
  true,
  true,
  false
),
(
  'Flyers & Brochures',
  'Flyers at Brochures',
  'Eye-catching flyers and brochures for your business or event. Full-color printing on quality paper. Perfect for promotions and information distribution.',
  'Nakakaakit na flyers at brochures para sa iyong negosyo o event. Full-color printing sa quality paper. Perpekto para sa promotions at information distribution.',
  'Professional flyers and brochures',
  'Propesyonal na flyers at brochures',
  'Printing Services',
  300.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Size": "8.5 x 11 inches", "Quantity": "100 pieces", "Paper": "Glossy"}'::jsonb,
  '3-5 business days',
  '3-5 araw ng negosyo',
  true,
  true,
  false
),

-- Souvenirs
(
  'Personalized Mugs',
  'Personalized na Mugs',
  'Custom-printed ceramic mugs perfect for gifts or promotional items. High-quality printing that won''t fade. Dishwasher safe and microwave safe.',
  'Custom-printed ceramic mugs na perpekto para sa gifts o promotional items. High-quality printing na hindi mapapawi. Dishwasher safe at microwave safe.',
  'Custom ceramic mugs with your design',
  'Custom ceramic mugs na may iyong disenyo',
  'Souvenirs',
  380.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Capacity": "11 oz", "Material": "Ceramic", "Printing": "Full wrap available"}'::jsonb,
  '5-7 business days',
  '5-7 araw ng negosyo',
  true,
  true,
  true
),
(
  'Custom Keychains',
  'Custom Keychains',
  'Durable acrylic keychains with custom designs. Perfect for giveaways, souvenirs, or personal use. Available in various shapes and sizes.',
  'Matibay na acrylic keychains na may custom designs. Perpekto para sa giveaways, souvenirs, o personal na gamit. Available sa iba''t ibang hugis at laki.',
  'Acrylic keychains with custom design',
  'Acrylic keychains na may custom design',
  'Souvenirs',
  120.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Material": "Acrylic", "Size": "2-3 inches", "Minimum Order": "10 pieces"}'::jsonb,
  '5-7 business days',
  '5-7 araw ng negosyo',
  true,
  true,
  false
),
(
  'Engraved Wood Plaques',
  'Engraved Wood Plaques',
  'Beautiful wooden plaques with laser engraving. Perfect for awards, recognition, or home decor. Made from quality wood with precise engraving.',
  'Magagandang wooden plaques na may laser engraving. Perpekto para sa awards, recognition, o home decor. Gawa sa quality wood na may precise engraving.',
  'Laser-engraved wooden plaques',
  'Laser-engraved wooden plaques',
  'Souvenirs',
  650.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Size": "8 x 10 inches", "Material": "Premium wood", "Finish": "Natural or stained"}'::jsonb,
  '7-10 business days',
  '7-10 araw ng negosyo',
  true,
  true,
  false
),
(
  'Gift Sets',
  'Gift Sets',
  'Curated gift sets perfect for any occasion. Includes a combination of our popular items beautifully packaged. Customizable to your preferences.',
  'Curated gift sets na perpekto para sa anumang okasyon. Kasama ang kombinasyon ng aming popular items na magandang nakabalot. Customizable ayon sa iyong preferences.',
  'Curated gift sets for any occasion',
  'Curated gift sets para sa anumang okasyon',
  'Souvenirs',
  950.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Contents": "Varies", "Packaging": "Premium gift box", "Customization": "Available"}'::jsonb,
  '7-10 business days',
  '7-10 araw ng negosyo',
  true,
  true,
  true
),

-- Invitations
(
  'Wedding Invitation Packages',
  'Wedding Invitation Packages',
  'Complete wedding invitation packages including save-the-dates, main invitations, RSVP cards, and thank you cards. Elegant designs customized to your wedding theme.',
  'Kumpletong wedding invitation packages kasama ang save-the-dates, main invitations, RSVP cards, at thank you cards. Elegant designs na customized sa tema ng iyong kasal.',
  'Complete wedding invitation packages',
  'Kumpletong wedding invitation packages',
  'Invitations',
  1200.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Includes": "Save-the-date, invitation, RSVP, thank you", "Quantity": "50 sets", "Paper": "Premium"}'::jsonb,
  '10-14 business days',
  '10-14 araw ng negosyo',
  true,
  true,
  true
),
(
  'Birthday Invitation Cards',
  'Birthday Invitation Cards',
  'Fun and colorful birthday invitations for all ages. Custom designs to match your party theme. High-quality printing on premium cardstock.',
  'Masaya at makulay na birthday invitations para sa lahat ng edad. Custom designs na tumutugma sa tema ng iyong party. High-quality printing sa premium cardstock.',
  'Custom birthday invitations',
  'Custom birthday invitations',
  'Invitations',
  280.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Size": "5 x 7 inches", "Quantity": "30 pieces", "Paper": "Cardstock"}'::jsonb,
  '5-7 business days',
  '5-7 araw ng negosyo',
  true,
  true,
  false
),

-- Digital Products
(
  'Printable Planner Templates',
  'Printable Planner Templates',
  'Digital planner templates ready to print. Includes monthly, weekly, and daily layouts. Perfect for staying organized. Instant download after purchase.',
  'Digital planner templates na ready to print. Kasama ang monthly, weekly, at daily layouts. Perpekto para sa pag-organize. Instant download pagkatapos ng pagbili.',
  'Digital planner templates for printing',
  'Digital planner templates para sa printing',
  'Digital Products',
  250.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Format": "PDF", "Pages": "50+", "Size": "A4 and Letter", "Delivery": "Instant download"}'::jsonb,
  'Instant download',
  'Instant download',
  false,
  true,
  false
),
(
  'Digital Logo Design Service',
  'Digital Logo Design Service',
  'Professional logo design service for your business or brand. Includes 3 initial concepts, unlimited revisions, and final files in multiple formats.',
  'Propesyonal na logo design service para sa iyong negosyo o brand. Kasama ang 3 initial concepts, unlimited revisions, at final files sa multiple formats.',
  'Professional logo design service',
  'Propesyonal na logo design service',
  'Digital Products',
  1500.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Concepts": "3 initial designs", "Revisions": "Unlimited", "Formats": "PNG, JPG, SVG, AI", "Delivery": "7-10 days"}'::jsonb,
  '7-10 business days',
  '7-10 araw ng negosyo',
  true,
  true,
  false
),
(
  'Social Media Template Pack',
  'Social Media Template Pack',
  'Ready-to-use social media templates for Instagram, Facebook, and more. Includes 30+ designs. Easily customizable in Canva. Perfect for consistent branding.',
  'Ready-to-use social media templates para sa Instagram, Facebook, at iba pa. Kasama ang 30+ designs. Madaling i-customize sa Canva. Perpekto para sa consistent branding.',
  '30+ social media templates',
  '30+ social media templates',
  'Digital Products',
  400.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Templates": "30+ designs", "Platforms": "Instagram, Facebook, Twitter", "Format": "Canva", "Delivery": "Instant"}'::jsonb,
  'Instant download',
  'Instant download',
  false,
  true,
  false
),
(
  'Digital Sticker Set',
  'Digital Sticker Set',
  'Cute digital sticker set for planners, journals, or digital use. Includes 50+ stickers in PNG format with transparent backgrounds. Instant download.',
  'Cute digital sticker set para sa planners, journals, o digital use. Kasama ang 50+ stickers sa PNG format na may transparent backgrounds. Instant download.',
  '50+ digital stickers for planners',
  '50+ digital stickers para sa planners',
  'Digital Products',
  200.00,
  'PHP',
  '["https://via.placeholder.com/500"]'::jsonb,
  '{"Stickers": "50+ designs", "Format": "PNG", "Background": "Transparent", "Delivery": "Instant"}'::jsonb,
  'Instant download',
  'Instant download',
  false,
  true,
  false
);
